eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8700/eureka
      instance:
         preferIpAddress: true
      registerWithEureka : true
      fetchRegistry : true
      
